// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'dart:typed_data' as prefix2;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:flutterusb/flutter_usb.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Response',
            r'.Response',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 12],
            const <int>[13, 14, 15, 16, 17, 6, 7, 8, 9, 10, 11],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => (result, outDataLength, inData) =>
                  b ? prefix1.Response(result, outDataLength, inData) : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'UsbDevice',
            r'.UsbDevice',
            7,
            1,
            const prefix0.JsonSerializable(),
            const <int>[3, 4, 5, 24],
            const <int>[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => (name, description, bstr) =>
                  b ? prefix1.UsbDevice(name, description, bstr) : null
            },
            -1,
            1,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'result',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.VariableMirrorImpl(
            r'outDataLength',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'inData',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4, const <int>[], const []),
        r.VariableMirrorImpl(
            r'name',
            32773,
            1,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.VariableMirrorImpl(
            r'description',
            32773,
            1,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.VariableMirrorImpl(
            r'bstr',
            32773,
            1,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 6),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 7),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 8),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 9),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 10),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 2, 11),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1, 2], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 5, 5, const <int>[],
            const <int>[6], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[7],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 3, 3, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            6,
            6,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 18),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 3, 19),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 4, 20),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 4, 21),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 5, 22),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 5, 23),
        r.MethodMirrorImpl(r'', 0, 1, -1, 1, 1, const <int>[],
            const <int>[8, 9, 10], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'result',
            32774,
            12,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'outDataLength',
            32774,
            12,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'inData',
            32774,
            12,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_result',
            32870,
            7,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_outDataLength',
            32870,
            9,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_inData',
            32870,
            11,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            13,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            15,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'name',
            32774,
            24,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'description',
            32774,
            24,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'bstr',
            32774,
            24,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_name',
            32870,
            19,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_description',
            32870,
            21,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_bstr',
            32870,
            23,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.Response,
        prefix1.UsbDevice,
        String,
        int,
        prefix2.Uint8List,
        bool,
        Type,
        Object,
        Invocation
      ],
      2,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'result': (dynamic instance) => instance.result,
        r'outDataLength': (dynamic instance) => instance.outDataLength,
        r'inData': (dynamic instance) => instance.inData,
        r'name': (dynamic instance) => instance.name,
        r'description': (dynamic instance) => instance.description,
        r'bstr': (dynamic instance) => instance.bstr
      },
      {
        r'result=': (dynamic instance, value) => instance.result = value,
        r'outDataLength=': (dynamic instance, value) =>
            instance.outDataLength = value,
        r'inData=': (dynamic instance, value) => instance.inData = value,
        r'name=': (dynamic instance, value) => instance.name = value,
        r'description=': (dynamic instance, value) =>
            instance.description = value,
        r'bstr=': (dynamic instance, value) => instance.bstr = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
